# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from s3m_apis_grpcio.status.v1alpha import status_pb2 as proto_dot_status_dot_v1alpha_dot_status__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/status/v1alpha/status_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StatusStub(object):
    """
    API

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListResources = channel.unary_unary(
                '/olcf.s3m.status.v1alpha.Status/ListResources',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_status_dot_v1alpha_dot_status__pb2.Resources.FromString,
                _registered_method=True)
        self.GetResource = channel.unary_unary(
                '/olcf.s3m.status.v1alpha.Status/GetResource',
                request_serializer=proto_dot_status_dot_v1alpha_dot_status__pb2.GetResourceRequest.SerializeToString,
                response_deserializer=proto_dot_status_dot_v1alpha_dot_status__pb2.Resource.FromString,
                _registered_method=True)
        self.ListDowntimesCurrent = channel.unary_unary(
                '/olcf.s3m.status.v1alpha.Status/ListDowntimesCurrent',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_status_dot_v1alpha_dot_status__pb2.Downtimes.FromString,
                _registered_method=True)
        self.ListDowntimesUpcoming = channel.unary_unary(
                '/olcf.s3m.status.v1alpha.Status/ListDowntimesUpcoming',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_status_dot_v1alpha_dot_status__pb2.Downtimes.FromString,
                _registered_method=True)


class StatusServicer(object):
    """
    API

    """

    def ListResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDowntimesCurrent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDowntimesUpcoming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListResources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListResources,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_status_dot_v1alpha_dot_status__pb2.Resources.SerializeToString,
            ),
            'GetResource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResource,
                    request_deserializer=proto_dot_status_dot_v1alpha_dot_status__pb2.GetResourceRequest.FromString,
                    response_serializer=proto_dot_status_dot_v1alpha_dot_status__pb2.Resource.SerializeToString,
            ),
            'ListDowntimesCurrent': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDowntimesCurrent,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_status_dot_v1alpha_dot_status__pb2.Downtimes.SerializeToString,
            ),
            'ListDowntimesUpcoming': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDowntimesUpcoming,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_status_dot_v1alpha_dot_status__pb2.Downtimes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'olcf.s3m.status.v1alpha.Status', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('olcf.s3m.status.v1alpha.Status', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Status(object):
    """
    API

    """

    @staticmethod
    def ListResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.status.v1alpha.Status/ListResources',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_status_dot_v1alpha_dot_status__pb2.Resources.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.status.v1alpha.Status/GetResource',
            proto_dot_status_dot_v1alpha_dot_status__pb2.GetResourceRequest.SerializeToString,
            proto_dot_status_dot_v1alpha_dot_status__pb2.Resource.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDowntimesCurrent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.status.v1alpha.Status/ListDowntimesCurrent',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_status_dot_v1alpha_dot_status__pb2.Downtimes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDowntimesUpcoming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.status.v1alpha.Status/ListDowntimesUpcoming',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_status_dot_v1alpha_dot_status__pb2.Downtimes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
