# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from s3m_apis_grpcio.slurm.v0044 import slurm_pb2 as proto_dot_slurm_dot_v0044_dot_slurm__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/slurm/v0044/slurm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SlurmIndirectStub(object):
    """
    API

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/olcf.s3m.slurm.v0044.SlurmIndirect/Ping',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.PingResp.FromString,
                _registered_method=True)
        self.GetDiag = channel.unary_unary(
                '/olcf.s3m.slurm.v0044.SlurmIndirect/GetDiag',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.DiagResp.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/olcf.s3m.slurm.v0044.SlurmIndirect/GetJob',
                request_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobIdReq.SerializeToString,
                response_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobIdResp.FromString,
                _registered_method=True)
        self.GetJobs = channel.unary_unary(
                '/olcf.s3m.slurm.v0044.SlurmIndirect/GetJobs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobsResp.FromString,
                _registered_method=True)
        self.PostJobSubmit = channel.unary_unary(
                '/olcf.s3m.slurm.v0044.SlurmIndirect/PostJobSubmit',
                request_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobSubmitReq.SerializeToString,
                response_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobSubmitResp.FromString,
                _registered_method=True)
        self.DeleteJob = channel.unary_unary(
                '/olcf.s3m.slurm.v0044.SlurmIndirect/DeleteJob',
                request_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.DeleteJobReq.SerializeToString,
                response_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.DeleteJobResp.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/olcf.s3m.slurm.v0044.SlurmIndirect/GetNodes',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.NodesResp.FromString,
                _registered_method=True)
        self.GetPartitions = channel.unary_unary(
                '/olcf.s3m.slurm.v0044.SlurmIndirect/GetPartitions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.PartitionsResp.FromString,
                _registered_method=True)
        self.GetReservations = channel.unary_unary(
                '/olcf.s3m.slurm.v0044.SlurmIndirect/GetReservations',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.ReservationsResp.FromString,
                _registered_method=True)


class SlurmIndirectServicer(object):
    """
    API

    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostJobSubmit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartitions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReservations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlurmIndirectServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.PingResp.SerializeToString,
            ),
            'GetDiag': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiag,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.DiagResp.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobIdReq.FromString,
                    response_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobIdResp.SerializeToString,
            ),
            'GetJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobsResp.SerializeToString,
            ),
            'PostJobSubmit': grpc.unary_unary_rpc_method_handler(
                    servicer.PostJobSubmit,
                    request_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobSubmitReq.FromString,
                    response_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobSubmitResp.SerializeToString,
            ),
            'DeleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteJob,
                    request_deserializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.DeleteJobReq.FromString,
                    response_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.DeleteJobResp.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.NodesResp.SerializeToString,
            ),
            'GetPartitions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartitions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.PartitionsResp.SerializeToString,
            ),
            'GetReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservations,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_slurm_dot_v0044_dot_slurm__pb2.ReservationsResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'olcf.s3m.slurm.v0044.SlurmIndirect', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('olcf.s3m.slurm.v0044.SlurmIndirect', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SlurmIndirect(object):
    """
    API

    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.slurm.v0044.SlurmIndirect/Ping',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.PingResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDiag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.slurm.v0044.SlurmIndirect/GetDiag',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.DiagResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.slurm.v0044.SlurmIndirect/GetJob',
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobIdReq.SerializeToString,
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobIdResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.slurm.v0044.SlurmIndirect/GetJobs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PostJobSubmit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.slurm.v0044.SlurmIndirect/PostJobSubmit',
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobSubmitReq.SerializeToString,
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.JobSubmitResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.slurm.v0044.SlurmIndirect/DeleteJob',
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.DeleteJobReq.SerializeToString,
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.DeleteJobResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.slurm.v0044.SlurmIndirect/GetNodes',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.NodesResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPartitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.slurm.v0044.SlurmIndirect/GetPartitions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.PartitionsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.slurm.v0044.SlurmIndirect/GetReservations',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_slurm_dot_v0044_dot_slurm__pb2.ReservationsResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
