# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from s3m_apis_grpcio.storage.v1alpha import storage_pb2 as proto_dot_storage_dot_v1alpha_dot_storage__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/storage/v1alpha/storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BucketGatewayStub(object):
    """
    API

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveDataset = channel.unary_unary(
                '/olcf.s3m.storage.v1alpha.BucketGateway/ReserveDataset',
                request_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.ReserveDatasetRequest.SerializeToString,
                response_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.ReserveDatasetResponse.FromString,
                _registered_method=True)
        self.CommitDataset = channel.unary_unary(
                '/olcf.s3m.storage.v1alpha.BucketGateway/CommitDataset',
                request_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.CommitDatasetRequest.SerializeToString,
                response_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.CommitDatasetResponse.FromString,
                _registered_method=True)
        self.DeleteDataset = channel.unary_unary(
                '/olcf.s3m.storage.v1alpha.BucketGateway/DeleteDataset',
                request_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.DeleteDatasetRequest.SerializeToString,
                response_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.DeleteDatasetResponse.FromString,
                _registered_method=True)
        self.ListDatasets = channel.unary_unary(
                '/olcf.s3m.storage.v1alpha.BucketGateway/ListDatasets',
                request_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.ListDatasetsRequest.SerializeToString,
                response_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.ListDatasetsResponse.FromString,
                _registered_method=True)
        self.GetDatasetContents = channel.unary_unary(
                '/olcf.s3m.storage.v1alpha.BucketGateway/GetDatasetContents',
                request_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDatasetContentsRequest.SerializeToString,
                response_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDatasetContentsResponse.FromString,
                _registered_method=True)
        self.GetDownloadURLs = channel.unary_unary(
                '/olcf.s3m.storage.v1alpha.BucketGateway/GetDownloadURLs',
                request_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDownloadURLsRequest.SerializeToString,
                response_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDownloadURLsResponse.FromString,
                _registered_method=True)


class BucketGatewayServicer(object):
    """
    API

    """

    def ReserveDataset(self, request, context):
        """Reserve a named dataset and return presigned PUT URLs for specified paths.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitDataset(self, request, context):
        """Mark a dataset as ready after uploads complete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDataset(self, request, context):
        """Tombstone a dataset and attempt deletion of backing objects.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDatasets(self, request, context):
        """List datasets within the caller's project.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetContents(self, request, context):
        """List files within a specific dataset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloadURLs(self, request, context):
        """Retrieve presigned GET URLs for specified paths in a dataset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BucketGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveDataset,
                    request_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.ReserveDatasetRequest.FromString,
                    response_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.ReserveDatasetResponse.SerializeToString,
            ),
            'CommitDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitDataset,
                    request_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.CommitDatasetRequest.FromString,
                    response_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.CommitDatasetResponse.SerializeToString,
            ),
            'DeleteDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDataset,
                    request_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.DeleteDatasetRequest.FromString,
                    response_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.DeleteDatasetResponse.SerializeToString,
            ),
            'ListDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDatasets,
                    request_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.ListDatasetsRequest.FromString,
                    response_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.ListDatasetsResponse.SerializeToString,
            ),
            'GetDatasetContents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetContents,
                    request_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDatasetContentsRequest.FromString,
                    response_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDatasetContentsResponse.SerializeToString,
            ),
            'GetDownloadURLs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloadURLs,
                    request_deserializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDownloadURLsRequest.FromString,
                    response_serializer=proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDownloadURLsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'olcf.s3m.storage.v1alpha.BucketGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('olcf.s3m.storage.v1alpha.BucketGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BucketGateway(object):
    """
    API

    """

    @staticmethod
    def ReserveDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.storage.v1alpha.BucketGateway/ReserveDataset',
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.ReserveDatasetRequest.SerializeToString,
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.ReserveDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.storage.v1alpha.BucketGateway/CommitDataset',
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.CommitDatasetRequest.SerializeToString,
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.CommitDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.storage.v1alpha.BucketGateway/DeleteDataset',
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.DeleteDatasetRequest.SerializeToString,
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.DeleteDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.storage.v1alpha.BucketGateway/ListDatasets',
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.ListDatasetsRequest.SerializeToString,
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.ListDatasetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDatasetContents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.storage.v1alpha.BucketGateway/GetDatasetContents',
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDatasetContentsRequest.SerializeToString,
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDatasetContentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDownloadURLs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.storage.v1alpha.BucketGateway/GetDownloadURLs',
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDownloadURLsRequest.SerializeToString,
            proto_dot_storage_dot_v1alpha_dot_storage__pb2.GetDownloadURLsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
