# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/common/v1alpha/gerr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/common/v1alpha/gerr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/common/v1alpha/gerr.proto\x12\x17olcf.s3m.common.v1alpha\"\xb8\x03\n\tGerrError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12:\n\x05\x63hild\x18\x02 \x01(\x0b\x32&.olcf.s3m.common.v1alpha.GerrErrorNodeH\x00\x88\x01\x01\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07private\x18\x04 \x01(\x08\x12\x1b\n\x0epublic_message\x18\x05 \x01(\tH\x01\x88\x01\x01\x12K\n\rpublic_fields\x18\x06 \x03(\x0b\x32\x34.olcf.s3m.common.v1alpha.GerrError.PublicFieldsEntry\x12M\n\x0eprivate_fields\x18\x07 \x03(\x0b\x32\x35.olcf.s3m.common.v1alpha.GerrError.PrivateFieldsEntry\x1a\x33\n\x11PublicFieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x34\n\x12PrivateFieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_childB\x11\n\x0f_public_message\"*\n\x0bGerrGoError\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x0c\n\x04kind\x18\x02 \x01(\t\"\x86\x01\n\rGerrErrorNode\x12\x33\n\x05\x65rror\x18\x01 \x01(\x0b\x32\".olcf.s3m.common.v1alpha.GerrErrorH\x00\x12\x38\n\x08go_error\x18\x02 \x01(\x0b\x32$.olcf.s3m.common.v1alpha.GerrGoErrorH\x00\x42\x06\n\x04node\"\x17\n\x15GerrPrivateDataMarkerB2Z0github.com/olcf/s3m-apis/common/v1alpha;commonpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common.v1alpha.gerr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/olcf/s3m-apis/common/v1alpha;commonpb'
  _globals['_GERRERROR_PUBLICFIELDSENTRY']._loaded_options = None
  _globals['_GERRERROR_PUBLICFIELDSENTRY']._serialized_options = b'8\001'
  _globals['_GERRERROR_PRIVATEFIELDSENTRY']._loaded_options = None
  _globals['_GERRERROR_PRIVATEFIELDSENTRY']._serialized_options = b'8\001'
  _globals['_GERRERROR']._serialized_start=61
  _globals['_GERRERROR']._serialized_end=501
  _globals['_GERRERROR_PUBLICFIELDSENTRY']._serialized_start=367
  _globals['_GERRERROR_PUBLICFIELDSENTRY']._serialized_end=418
  _globals['_GERRERROR_PRIVATEFIELDSENTRY']._serialized_start=420
  _globals['_GERRERROR_PRIVATEFIELDSENTRY']._serialized_end=472
  _globals['_GERRGOERROR']._serialized_start=503
  _globals['_GERRGOERROR']._serialized_end=545
  _globals['_GERRERRORNODE']._serialized_start=548
  _globals['_GERRERRORNODE']._serialized_end=682
  _globals['_GERRPRIVATEDATAMARKER']._serialized_start=684
  _globals['_GERRPRIVATEDATAMARKER']._serialized_end=707
# @@protoc_insertion_point(module_scope)
