# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/common/v1alpha/headers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/common/v1alpha/headers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"proto/common/v1alpha/headers.proto\x12\x17olcf.s3m.common.v1alpha\x1a google/protobuf/descriptor.proto\"C\n\x0bHeaderParam\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x12\n\nparam_name\x18\x02 \x01(\t\x12\x10\n\x08required\x18\x03 \x01(\x08:c\n\x13method_header_param\x12\x1e.google.protobuf.MethodOptions\x18\xc4\x9d\t \x03(\x0b\x32$.olcf.s3m.common.v1alpha.HeaderParam:e\n\x14service_header_param\x12\x1f.google.protobuf.ServiceOptions\x18\xc5\x9d\t \x03(\x0b\x32$.olcf.s3m.common.v1alpha.HeaderParamB2Z0github.com/olcf/s3m-apis/common/v1alpha;commonpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common.v1alpha.headers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/olcf/s3m-apis/common/v1alpha;commonpb'
  _globals['_HEADERPARAM']._serialized_start=97
  _globals['_HEADERPARAM']._serialized_end=164
# @@protoc_insertion_point(module_scope)
