# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from s3m_apis_grpcio.tms.v1 import control_pb2 as proto_dot_tms_dot_v1_dot_control__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/tms/v1/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TokenControlStub(object):
    """
    API

    The TokenControl service allows for a supplied token (auth header/metadata) to perform
    limited actions on itself or retrieve additional details.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntrospectAuthToken = channel.unary_unary(
                '/olcf.s3m.tms.v1.TokenControl/IntrospectAuthToken',
                request_serializer=proto_dot_tms_dot_v1_dot_control__pb2.IntrospectAuthTokenRequest.SerializeToString,
                response_deserializer=proto_dot_tms_dot_v1_dot_control__pb2.IntrospectAuthTokenResponse.FromString,
                _registered_method=True)
        self.RevokeAuthToken = channel.unary_unary(
                '/olcf.s3m.tms.v1.TokenControl/RevokeAuthToken',
                request_serializer=proto_dot_tms_dot_v1_dot_control__pb2.RevokeAuthTokenRequest.SerializeToString,
                response_deserializer=proto_dot_tms_dot_v1_dot_control__pb2.RevokeAuthTokenResponse.FromString,
                _registered_method=True)


class TokenControlServicer(object):
    """
    API

    The TokenControl service allows for a supplied token (auth header/metadata) to perform
    limited actions on itself or retrieve additional details.
    """

    def IntrospectAuthToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAuthToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TokenControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IntrospectAuthToken': grpc.unary_unary_rpc_method_handler(
                    servicer.IntrospectAuthToken,
                    request_deserializer=proto_dot_tms_dot_v1_dot_control__pb2.IntrospectAuthTokenRequest.FromString,
                    response_serializer=proto_dot_tms_dot_v1_dot_control__pb2.IntrospectAuthTokenResponse.SerializeToString,
            ),
            'RevokeAuthToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAuthToken,
                    request_deserializer=proto_dot_tms_dot_v1_dot_control__pb2.RevokeAuthTokenRequest.FromString,
                    response_serializer=proto_dot_tms_dot_v1_dot_control__pb2.RevokeAuthTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'olcf.s3m.tms.v1.TokenControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('olcf.s3m.tms.v1.TokenControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TokenControl(object):
    """
    API

    The TokenControl service allows for a supplied token (auth header/metadata) to perform
    limited actions on itself or retrieve additional details.
    """

    @staticmethod
    def IntrospectAuthToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.tms.v1.TokenControl/IntrospectAuthToken',
            proto_dot_tms_dot_v1_dot_control__pb2.IntrospectAuthTokenRequest.SerializeToString,
            proto_dot_tms_dot_v1_dot_control__pb2.IntrospectAuthTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAuthToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.tms.v1.TokenControl/RevokeAuthToken',
            proto_dot_tms_dot_v1_dot_control__pb2.RevokeAuthTokenRequest.SerializeToString,
            proto_dot_tms_dot_v1_dot_control__pb2.RevokeAuthTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
