# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/tms/v1/control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/tms/v1/control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/tms/v1/control.proto\x12\x0folcf.s3m.tms.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"6\n\x1aIntrospectAuthTokenRequest\x12\x18\n\x10grpc_permissions\x18\x01 \x01(\x08\"X\n\x1bIntrospectAuthTokenResponse\x12\x39\n\x05token\x18\x01 \x01(\x0b\x32*.olcf.s3m.tms.v1.TokenDetailsIntrospective\"\x18\n\x16RevokeAuthTokenRequest\"\x19\n\x17RevokeAuthTokenResponse\"\xfd\x02\n\x19TokenDetailsIntrospective\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x13\n\x0bpermissions\x18\x03 \x03(\t\x12\x36\n\x12planned_expiration\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10security_enclave\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x16\n\x0eone_time_token\x18\x07 \x01(\x08\x12\x15\n\rdelayed_start\x18\x08 \x01(\x08\x12.\n\ndelay_date\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nowner_name\x18\n \x01(\t\x12:\n\x10grpc_permissions\x18\x0b \x03(\x0b\x32 .olcf.s3m.tms.v1.GRPCPermissions\x12\x12\n\nextensions\x18\x0c \x01(\x05\"3\n\x0fGRPCPermissions\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x12\n\npermission\x18\x02 \x01(\t2\xb4\x02\n\x0cTokenControl\x12\x98\x01\n\x13IntrospectAuthToken\x12+.olcf.s3m.tms.v1.IntrospectAuthTokenRequest\x1a,.olcf.s3m.tms.v1.IntrospectAuthTokenResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/olcf/v1/token/ctls/introspect\x12\x88\x01\n\x0fRevokeAuthToken\x12\'.olcf.s3m.tms.v1.RevokeAuthTokenRequest\x1a(.olcf.s3m.tms.v1.RevokeAuthTokenResponse\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/olcf/v1/token/ctls/revokeB\'Z%github.com/olcf/s3m-apis/tms/v1;tmspbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.tms.v1.control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/olcf/s3m-apis/tms/v1;tmspb'
  _globals['_TOKENCONTROL'].methods_by_name['IntrospectAuthToken']._loaded_options = None
  _globals['_TOKENCONTROL'].methods_by_name['IntrospectAuthToken']._serialized_options = b'\202\323\344\223\002 \022\036/olcf/v1/token/ctls/introspect'
  _globals['_TOKENCONTROL'].methods_by_name['RevokeAuthToken']._loaded_options = None
  _globals['_TOKENCONTROL'].methods_by_name['RevokeAuthToken']._serialized_options = b'\202\323\344\223\002\034*\032/olcf/v1/token/ctls/revoke'
  _globals['_INTROSPECTAUTHTOKENREQUEST']._serialized_start=110
  _globals['_INTROSPECTAUTHTOKENREQUEST']._serialized_end=164
  _globals['_INTROSPECTAUTHTOKENRESPONSE']._serialized_start=166
  _globals['_INTROSPECTAUTHTOKENRESPONSE']._serialized_end=254
  _globals['_REVOKEAUTHTOKENREQUEST']._serialized_start=256
  _globals['_REVOKEAUTHTOKENREQUEST']._serialized_end=280
  _globals['_REVOKEAUTHTOKENRESPONSE']._serialized_start=282
  _globals['_REVOKEAUTHTOKENRESPONSE']._serialized_end=307
  _globals['_TOKENDETAILSINTROSPECTIVE']._serialized_start=310
  _globals['_TOKENDETAILSINTROSPECTIVE']._serialized_end=691
  _globals['_GRPCPERMISSIONS']._serialized_start=693
  _globals['_GRPCPERMISSIONS']._serialized_end=744
  _globals['_TOKENCONTROL']._serialized_start=747
  _globals['_TOKENCONTROL']._serialized_end=1055
# @@protoc_insertion_point(module_scope)
