# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/streaming/v1alpha/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/streaming/v1alpha/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$proto/streaming/v1alpha/common.proto\x12\x1aolcf.s3m.streaming.v1alpha\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n\x15\x42\x61\x63kendResourceOption\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0b\n\x03min\x18\x03 \x01(\x05\x12\x0b\n\x03max\x18\x04 \x01(\x05\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x05 \x01(\x05\"G\n\x12\x42\x61\x63kendFeatureFlag\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65\x66\x61ult\x18\x03 \x01(\x08\"\x93\x01\n\x0c\x41ppEndpoints\x12\x11\n\taddresses\x18\x01 \x03(\t\x12\x42\n\x05ports\x18\x02 \x03(\x0b\x32\x33.olcf.s3m.streaming.v1alpha.AppEndpoints.PortsEntry\x1a,\n\nPortsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"\xa4\x01\n\x08Lifetime\x12\x32\n\x0eprovisioned_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0b\x65xtended_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10seconds_lifetime\x18\x03 \x01(\r\x12\x19\n\x11seconds_remaining\x18\x04 \x01(\rB8Z6github.com/olcf/s3m-apis/streaming/v1alpha;streamingpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.streaming.v1alpha.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/olcf/s3m-apis/streaming/v1alpha;streamingpb'
  _globals['_APPENDPOINTS_PORTSENTRY']._loaded_options = None
  _globals['_APPENDPOINTS_PORTSENTRY']._serialized_options = b'8\001'
  _globals['_BACKENDRESOURCEOPTION']._serialized_start=101
  _globals['_BACKENDRESOURCEOPTION']._serialized_end=201
  _globals['_BACKENDFEATUREFLAG']._serialized_start=203
  _globals['_BACKENDFEATUREFLAG']._serialized_end=274
  _globals['_APPENDPOINTS']._serialized_start=277
  _globals['_APPENDPOINTS']._serialized_end=424
  _globals['_APPENDPOINTS_PORTSENTRY']._serialized_start=380
  _globals['_APPENDPOINTS_PORTSENTRY']._serialized_end=424
  _globals['_LIFETIME']._serialized_start=427
  _globals['_LIFETIME']._serialized_end=591
# @@protoc_insertion_point(module_scope)
