# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from s3m_apis_grpcio.streaming.v1alpha import rabbitmq_pb2 as proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2
from s3m_apis_grpcio.streaming.v1alpha import redis_pb2 as proto_dot_streaming_dot_v1alpha_dot_redis__pb2
from s3m_apis_grpcio.streaming.v1alpha import streaming_pb2 as proto_dot_streaming_dot_v1alpha_dot_streaming__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/streaming/v1alpha/streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingStub(object):
    """
    API

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBackends = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.Streaming/ListBackends',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_streaming__pb2.ListBackendsRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_streaming__pb2.ListBackendsResponse.FromString,
                _registered_method=True)


class StreamingServicer(object):
    """
    API

    """

    def ListBackends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBackends': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBackends,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_streaming__pb2.ListBackendsRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_streaming__pb2.ListBackendsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'olcf.s3m.streaming.v1alpha.Streaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('olcf.s3m.streaming.v1alpha.Streaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Streaming(object):
    """
    API

    """

    @staticmethod
    def ListBackends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.Streaming/ListBackends',
            proto_dot_streaming_dot_v1alpha_dot_streaming__pb2.ListBackendsRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_streaming__pb2.ListBackendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RabbitMQStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProvisionRabbitMQCluster = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ProvisionRabbitMQCluster',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ProvisionRabbitMQClusterRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ProvisionRabbitMQClusterResponse.FromString,
                _registered_method=True)
        self.ListRabbitMQClusters = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ListRabbitMQClusters',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ListRabbitMQClustersRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ListRabbitMQClustersResponse.FromString,
                _registered_method=True)
        self.GetRabbitMQCluster = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/GetRabbitMQCluster',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.GetRabbitMQClusterRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.GetRabbitMQClusterResponse.FromString,
                _registered_method=True)
        self.DeleteRabbitMQCluster = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/DeleteRabbitMQCluster',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.DeleteRabbitMQClusterRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.DeleteRabbitMQClusterResponse.FromString,
                _registered_method=True)
        self.ExtendRabbitMQClusterLife = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ExtendRabbitMQClusterLife',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ExtendRabbitMQClusterLifeRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ExtendRabbitMQClusterLifeResponse.FromString,
                _registered_method=True)


class RabbitMQStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProvisionRabbitMQCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRabbitMQClusters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRabbitMQCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRabbitMQCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtendRabbitMQClusterLife(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RabbitMQStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProvisionRabbitMQCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvisionRabbitMQCluster,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ProvisionRabbitMQClusterRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ProvisionRabbitMQClusterResponse.SerializeToString,
            ),
            'ListRabbitMQClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRabbitMQClusters,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ListRabbitMQClustersRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ListRabbitMQClustersResponse.SerializeToString,
            ),
            'GetRabbitMQCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRabbitMQCluster,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.GetRabbitMQClusterRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.GetRabbitMQClusterResponse.SerializeToString,
            ),
            'DeleteRabbitMQCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRabbitMQCluster,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.DeleteRabbitMQClusterRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.DeleteRabbitMQClusterResponse.SerializeToString,
            ),
            'ExtendRabbitMQClusterLife': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtendRabbitMQClusterLife,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ExtendRabbitMQClusterLifeRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ExtendRabbitMQClusterLifeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'olcf.s3m.streaming.v1alpha.RabbitMQStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('olcf.s3m.streaming.v1alpha.RabbitMQStreaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RabbitMQStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProvisionRabbitMQCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ProvisionRabbitMQCluster',
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ProvisionRabbitMQClusterRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ProvisionRabbitMQClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRabbitMQClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ListRabbitMQClusters',
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ListRabbitMQClustersRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ListRabbitMQClustersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRabbitMQCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/GetRabbitMQCluster',
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.GetRabbitMQClusterRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.GetRabbitMQClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRabbitMQCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/DeleteRabbitMQCluster',
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.DeleteRabbitMQClusterRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.DeleteRabbitMQClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtendRabbitMQClusterLife(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ExtendRabbitMQClusterLife',
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ExtendRabbitMQClusterLifeRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_rabbitmq__pb2.ExtendRabbitMQClusterLifeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RedisStreamingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProvisionRedisCluster = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RedisStreaming/ProvisionRedisCluster',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ProvisionRedisClusterRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ProvisionRedisClusterResponse.FromString,
                _registered_method=True)
        self.ListRedisClusters = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RedisStreaming/ListRedisClusters',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ListRedisClustersRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ListRedisClustersResponse.FromString,
                _registered_method=True)
        self.GetRedisCluster = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RedisStreaming/GetRedisCluster',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.GetRedisClusterRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.GetRedisClusterResponse.FromString,
                _registered_method=True)
        self.DeleteRedisCluster = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RedisStreaming/DeleteRedisCluster',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.DeleteRedisClusterRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.DeleteRedisClusterResponse.FromString,
                _registered_method=True)
        self.ExtendRedisClusterLife = channel.unary_unary(
                '/olcf.s3m.streaming.v1alpha.RedisStreaming/ExtendRedisClusterLife',
                request_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ExtendRedisClusterLifeRequest.SerializeToString,
                response_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ExtendRedisClusterLifeResponse.FromString,
                _registered_method=True)


class RedisStreamingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProvisionRedisCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRedisClusters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRedisCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRedisCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtendRedisClusterLife(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RedisStreamingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProvisionRedisCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvisionRedisCluster,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ProvisionRedisClusterRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ProvisionRedisClusterResponse.SerializeToString,
            ),
            'ListRedisClusters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRedisClusters,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ListRedisClustersRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ListRedisClustersResponse.SerializeToString,
            ),
            'GetRedisCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRedisCluster,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.GetRedisClusterRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.GetRedisClusterResponse.SerializeToString,
            ),
            'DeleteRedisCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRedisCluster,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.DeleteRedisClusterRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.DeleteRedisClusterResponse.SerializeToString,
            ),
            'ExtendRedisClusterLife': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtendRedisClusterLife,
                    request_deserializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ExtendRedisClusterLifeRequest.FromString,
                    response_serializer=proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ExtendRedisClusterLifeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'olcf.s3m.streaming.v1alpha.RedisStreaming', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('olcf.s3m.streaming.v1alpha.RedisStreaming', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RedisStreaming(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProvisionRedisCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RedisStreaming/ProvisionRedisCluster',
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ProvisionRedisClusterRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ProvisionRedisClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRedisClusters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RedisStreaming/ListRedisClusters',
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ListRedisClustersRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ListRedisClustersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRedisCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RedisStreaming/GetRedisCluster',
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.GetRedisClusterRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.GetRedisClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRedisCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RedisStreaming/DeleteRedisCluster',
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.DeleteRedisClusterRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.DeleteRedisClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtendRedisClusterLife(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/olcf.s3m.streaming.v1alpha.RedisStreaming/ExtendRedisClusterLife',
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ExtendRedisClusterLifeRequest.SerializeToString,
            proto_dot_streaming_dot_v1alpha_dot_redis__pb2.ExtendRedisClusterLifeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
